# Generated by Django 5.0.1 on 2024-05-01 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookMng", "0003_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="favorites",
            field=models.ManyToManyField(
                related_name="favorite_books", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
