# Generated by Django 5.0.1 on 2024-05-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookMng", "0004_book_favorites"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="genres",
            field=models.ManyToManyField(to="bookMng.genre"),
        ),
    ]
